---
name: Prepare, build and run tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install needed packages
        run: |
          sudo apt update
          sudo apt install -y git \
                              build-essential \
                              cmake \
                              clang \
                              meson \
                              pkg-config

      - name: Compile and install Criterion
        run: |
          git submodule update --init --recursive
          cd extern/Criterion
          meson build
          ninja -C build
          sudo ninja -C build install

      - name: Build
        run: |
          cd build
          cmake ..
          cmake --build .

      - name: Run tests
        run: |
          cd build/test
          ./c_katas_test

  build-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install homebrew
        run: |
          NONINTERACTIVE=1
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Install needed software
        run: |
          brew update && \
          brew install cmake \
                       gcc \
                       meson \
                       pkg-config

      - name: Compile and install Criterion
        run: |
          git submodule update --init --recursive
          cd extern/Criterion
          meson build
          ninja -C build
          sudo ninja -C build install

      - name: Build
        run: |
          cd build
          export C_INCLUDE_PATH=/usr/local/include
          cmake ..
          cmake --build .

      - name: Run tests
        run: |
          cd build/test
          ./c_katas_test
